# Generated by Django 4.0.5 on 2022-08-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=10)),
                ('dni', models.IntegerField(unique=True)),
                ('celular', models.IntegerField()),
                ('mail', models.EmailField(blank=True, max_length=30, null=True)),
                ('tallepantalon', models.IntegerField(blank=True, null=True)),
                ('tallezapatos', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vestimenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ropa', models.BooleanField(max_length=10)),
                ('zapatos', models.BooleanField(max_length=10)),
                ('pulsera', models.BooleanField(max_length=10)),
            ],
        ),
    ]
